Repository gae-jang-mo/app, pull requests merged in 2019-12, with the labels that each got.

#4 [#3] 시큐리티 설정 적용
  build.gradle
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
Labels: enhancement

#10 Feature/7 product setting
  build.gradle
  src/main/java/com/gaejangmo/apiserver/model/common/BaseEntity.java
  src/main/java/com/gaejangmo/apiserver/model/product/controller/ProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/Product.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/ProductRepository.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/Link.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/MallName.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/NaverProductType.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/Price.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductId.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductName.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductType.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/ProductRequestDto.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/ProductResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/ProductSearchDto.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/validator/EnumValidator.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/validator/EnumValue.java
  src/main/java/com/gaejangmo/apiserver/model/product/exception/EmptyValueException.java
  src/main/java/com/gaejangmo/apiserver/model/product/exception/NaverProductTypeNotFoundException.java
  src/main/java/com/gaejangmo/apiserver/model/product/exception/ProductTypeNotFoundException.java
  src/main/java/com/gaejangmo/apiserver/model/product/exception/UrlFormatException.java
  src/main/java/com/gaejangmo/apiserver/model/product/service/ProductService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductAcceptanceTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/ProductTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/vo/LinkTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/vo/MallNameTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/vo/PriceTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductIdTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductNameTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/service/ProductServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/testdata/ProductTestData.java
Labels: enhancement

#18 Feature/9 oauth
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/ProviderAttributes.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/dto/OAuthAttributesDto.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/exception/NotExistedProviderException.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/service/OAuth2Service.java
  src/main/java/com/gaejangmo/apiserver/model/common/controller/IndexController.java
  src/main/java/com/gaejangmo/apiserver/model/common/domain/BaseEntity.java
  src/main/java/com/gaejangmo/apiserver/model/common/domain/vo/Link.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/Product.java
  src/main/java/com/gaejangmo/apiserver/model/product/service/ProductService.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/SignApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/UserRepository.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/converter/GradeAttributeConverter.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/converter/RoleAttributeConverter.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/exception/NotFoundGradeException.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/exception/RoleNotFoundException.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/vo/Email.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/vo/Grade.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/vo/Motto.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/vo/Role.java
  src/main/java/com/gaejangmo/apiserver/model/user/exception/InvalidEmailException.java
  src/main/java/com/gaejangmo/apiserver/model/user/exception/InvalidMottoException.java
  src/main/resources/bootstrap.yml
  src/test/java/com/gaejangmo/apiserver/ApiServerApplicationTests.java
  src/test/java/com/gaejangmo/apiserver/model/common/domain/vo/LinkTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductAcceptanceTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/domain/ProductTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/testdata/ProductTestData.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/SignApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/domain/UserTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/domain/vo/EmailTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/domain/vo/MottoTest.java
Labels: refactor

#22 Feature/8 user product
  build.gradle
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
  src/main/java/com/gaejangmo/apiserver/config/WebMvcConfig.java
  src/main/java/com/gaejangmo/apiserver/config/oauth/service/OAuth2Service.java
  src/main/java/com/gaejangmo/apiserver/model/common/exception/NotLoginException.java
  src/main/java/com/gaejangmo/apiserver/model/common/resolver/LoginUser.java
  src/main/java/com/gaejangmo/apiserver/model/common/resolver/SessionUser.java
  src/main/java/com/gaejangmo/apiserver/model/common/resolver/SessionUserArgumentResolver.java
  src/main/java/com/gaejangmo/apiserver/model/product/service/ProductService.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/converter/ProductTypeConverter.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/UserProduct.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/UserProductRepository.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/converter/ProductTypeAttributeConverter.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/exception/AlreadyDeleteException.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/exception/ProductTypeNotFoundException.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/Comment.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/ProductType.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/dto/UserProductCreateDto.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/dto/UserProductResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/exception/NotUserProductOwnerException.java
  src/test/java/com/gaejangmo/apiserver/model/user/domain/UserTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductAcceptanceTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/converter/ProductTypeConverterTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/domain/UserProductTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/domain/converter/ProductTypeAttributeConverterTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/CommentTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/ProductTypeTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductServiceTest.java
Labels: enhancement

#26 Refactor/24 refactoring
  src/main/java/com/gaejangmo/apiserver/config/JpaConfig.java
  src/main/java/com/gaejangmo/apiserver/model/common/domain/BaseTimeEntity.java
  src/main/java/com/gaejangmo/apiserver/model/common/exception/ApiErrorResponse.java
  src/main/java/com/gaejangmo/apiserver/model/common/exception/NotLoginException.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/Product.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/UserProduct.java
  src/main/resources/application.yml
Labels: refactor

#31 Fix/29 test profile setting
  build.gradle
  src/main/resources/application.yml
  src/main/resources/bootstrap.yml
  src/test/java/com/gaejangmo/apiserver/ApiServerApplicationTests.java
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/SignApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
Labels: bug

#12 Feature/11 AOP를 이용한 Controller, ControllerAdvice 로깅
  src/main/java/com/gaejangmo/apiserver/commons/logging/EnableLog.java
  src/main/java/com/gaejangmo/apiserver/commons/logging/LoggingAspect.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/main/resources/application.yml
Labels: enhancement

#35 Fix/34 user conflict
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
Labels: bug

#42 Fix/38 extract oauth redirect url
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#43 Featuer/28 s3 image
  .gitignore
  build.gradle
  src/main/java/com/gaejangmo/apiserver/config/aws/AwsConfig.java
  src/main/java/com/gaejangmo/apiserver/config/aws/S3Connector.java
  src/main/java/com/gaejangmo/apiserver/config/aws/exception/S3FileUploadException.java
  src/main/java/com/gaejangmo/apiserver/model/common/resolver/SessionUser.java
  src/main/java/com/gaejangmo/apiserver/model/image/domain/UploadImage.java
  src/main/java/com/gaejangmo/apiserver/model/image/domain/user/service/UserImageService.java
  src/main/java/com/gaejangmo/apiserver/model/image/domain/vo/FileFeature.java
  src/main/java/com/gaejangmo/apiserver/model/image/domain/vo/ImageType.java
  src/main/java/com/gaejangmo/apiserver/model/image/dto/FileResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/image/user/domain/UserImage.java
  src/main/java/com/gaejangmo/apiserver/model/image/user/domain/UserImageRepository.java
  src/main/java/com/gaejangmo/apiserver/model/image/utils/ImageTypeValidator.java
  src/main/java/com/gaejangmo/apiserver/model/image/utils/UploadFileNameCreator.java
  src/main/java/com/gaejangmo/apiserver/model/image/utils/UploadFileNameUuidCreator.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/Comment.java
  src/main/resources/application.yml
  src/test/java/com/gaejangmo/apiserver/config/aws/S3ConnectorTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/domain/user/service/UserImageServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/domain/vo/FileFeatureTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/domain/vo/ImageTypeTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/utils/ImageTypeValidatorTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/utils/UploadFileNameUuidCreatorTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiControllerTest.java
Labels: enhancement

#55 Featur/54 spring rest docs preprocessor
  src/docs/asciidoc/index.adoc
  src/test/java/com/gaejangmo/apiserver/model/common/support/ApiDocumentUtils.java
Labels: enhancement

#63 fix: img 경로 Security 예외추가
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
Labels: bug

#59 Feature/47 notice
  src/docs/asciidoc/index.adoc
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
  src/main/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiController.java
  src/main/java/com/gaejangmo/apiserver/model/notice/domain/Notice.java
  src/main/java/com/gaejangmo/apiserver/model/notice/domain/NoticeRepository.java
  src/main/java/com/gaejangmo/apiserver/model/notice/domain/NoticeType.java
  src/main/java/com/gaejangmo/apiserver/model/notice/domain/converter/NoticeTypeConverter.java
  src/main/java/com/gaejangmo/apiserver/model/notice/dto/NoticeRequestDto.java
  src/main/java/com/gaejangmo/apiserver/model/notice/dto/NoticeResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/notice/exception/NoticeTypeNotFoundException.java
  src/main/java/com/gaejangmo/apiserver/model/notice/service/NoticeService.java
  src/test/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/notice/domain/NoticeTest.java
  src/test/java/com/gaejangmo/apiserver/model/notice/testdata/NoticeTestData.java
Labels: enhancement

#60 Feature/53 로그 관리 전략
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: enhancement

#56 Feature/50 user rest docs
  src/docs/asciidoc/index.adoc
  src/main/java/com/gaejangmo/apiserver/config/SecurityConfig.java
  src/main/java/com/gaejangmo/apiserver/model/image/dto/FileResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/User.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/vo/Motto.java
  src/test/java/com/gaejangmo/apiserver/model/MockMvcTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/SignApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/domain/UserTest.java
Labels: enhancement

#68 Feature/67 operation preprocessor
  src/docs/asciidoc/index.adoc
  src/test/java/com/gaejangmo/apiserver/model/common/support/ApiDocumentUtils.java
  src/test/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/product/controller/ProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/SignApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
Labels: enhancement

#70 username으로 검색 API
  src/docs/asciidoc/index.adoc
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/UserRepository.java
  src/main/java/com/gaejangmo/apiserver/model/user/dto/UserSearchDto.java
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/service/UserServiceTest.java
  src/test/resources/data.sql
Labels: enhancement

#74 feat: Notice pageable 적용
  src/main/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiController.java
  src/main/java/com/gaejangmo/apiserver/model/notice/service/NoticeService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/test/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiControllerTest.java
  src/test/resources/data.sql
Labels: enhancement

#77 fix: UserImageService 저장되는 파일이름 수정
  src/main/java/com/gaejangmo/apiserver/model/image/domain/user/service/UserImageService.java
Labels: bug

#79 refactor: conflict 해결
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductService.java
  src/test/resources/data.sql
Labels: bug

#82 Feature/66 pick random users
  build.gradle
  src/main/java/com/gaejangmo/apiserver/model/product/dto/ManagedProductResponseDto.java
  src/main/java/com/gaejangmo/apiserver/model/product/dto/ProductRequestDto.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/domain/UserRepository.java
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/service/UserServiceTest.java
Labels: enhancement

#83 Feature/80 additional like
  src/docs/asciidoc/index.adoc
  src/main/java/com/gaejangmo/apiserver/model/like/controller/LikeController.java
  src/main/java/com/gaejangmo/apiserver/model/like/exception/InvalidMySelfLikeException.java
  src/main/java/com/gaejangmo/apiserver/model/like/service/LikeService.java
  src/main/java/com/gaejangmo/apiserver/model/notice/controller/NoticeApiController.java
  src/main/java/com/gaejangmo/apiserver/model/product/controller/ProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/test/java/com/gaejangmo/apiserver/model/like/controller/LikeControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/like/service/LikeServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
Labels: enhancement

#86 Feature/85 get product type with name
  src/main/java/com/gaejangmo/apiserver/model/product/controller/ProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductType.java
Labels: enhancement

#93 refactor: 유저 검색 빈값 처리
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/test/java/com/gaejangmo/apiserver/model/user/service/UserServiceTest.java
Labels: bug

#96 Feature/90 api refactor
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/dto/UserProductResponseDto.java
  src/test/java/com/gaejangmo/apiserver/model/user/service/UserServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductServiceTest.java
  src/test/resources/data.sql
Labels: refactor

#97 test yml loading 경로 변경
  src/main/resources/bootstrap.yml
Labels: bug

#105 NaverProductType 저장 에러해결
  src/main/java/com/gaejangmo/apiserver/model/product/domain/Product.java
  src/main/java/com/gaejangmo/apiserver/model/product/service/ProductService.java
Labels: bug

#111 Feature/101 like refactoring
  src/main/java/com/gaejangmo/apiserver/model/common/domain/vo/Link.java
  src/main/java/com/gaejangmo/apiserver/model/common/resolver/SecurityUserArgumentResolver.java
  src/main/java/com/gaejangmo/apiserver/model/like/service/LikeService.java
  src/main/java/com/gaejangmo/apiserver/model/notice/domain/Notice.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/MallName.java
  src/main/java/com/gaejangmo/apiserver/model/product/domain/vo/ProductName.java
  src/main/java/com/gaejangmo/apiserver/model/user/controller/UserApiController.java
  src/main/java/com/gaejangmo/apiserver/model/user/service/UserService.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiController.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/domain/vo/Comment.java
  src/main/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductService.java
  src/main/resources/logback-spring.xml
  src/test/java/com/gaejangmo/apiserver/model/image/domain/vo/FileFeatureTest.java
  src/test/java/com/gaejangmo/apiserver/model/image/utils/ImageTypeValidatorTest.java
  src/test/java/com/gaejangmo/apiserver/model/like/service/LikeServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/notice/domain/NoticeTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/service/UserServiceTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/controller/UserProductApiControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/userproduct/service/UserProductServiceTest.java
Labels: refactor

#115 feat: User Ranking 구현
  src/main/java/com/gaejangmo/apiserver/model/like/controller/LikeController.java
  src/main/java/com/gaejangmo/apiserver/model/like/domain/LikeRepository.java
  src/main/java/com/gaejangmo/apiserver/model/like/service/LikeService.java
  src/test/java/com/gaejangmo/apiserver/model/like/controller/LikeControllerTest.java
  src/test/java/com/gaejangmo/apiserver/model/user/controller/UserApiControllerTest.java
  src/test/resources/data.sql
Labels: enhancement

#128 S3Connector 수정
  src/main/java/com/gaejangmo/apiserver/config/aws/S3Connector.java
Labels: bug
